### ISSUE TITLE
Exception activating extension with sortier 1.0.1

### ISSUE THREAD

**Issue by jpaas** [snowcoders/sortier-vscode#723]
After upgrading to sortier 1.0.1 the extension was no longer running sortier on save.

I tried manually running the sortier vscode command but got an error that read `Command 'Sortier: Run' resulted in an error (command 'sortier.run' not found)`

I went poking around in the extension host log and found this stack trace

```
[2021-12-22 09:07:57.284] [exthost] [info] ExtensionService#_doActivateExtension Snowcoders.sortier-vscode, startup: false, activationEvent: 'onStartupFinished'
[2021-12-22 09:07:58.019] [exthost] [error] Activating extension Snowcoders.sortier-vscode failed due to an error:
[2021-12-22 09:07:58.020] [exthost] [error] TypeError: Cannot read property 'process' of undefined
    at /Users/jpaas/.vscode/extensions/snowcoders.sortier-vscode-2.0.2/dist/extension.js:202:28547
    at /Users/jpaas/.vscode/extensions/snowcoders.sortier-vscode-2.0.2/dist/extension.js:208:1101020
    at /Users/jpaas/.vscode/extensions/snowcoders.sortier-vscode-2.0.2/dist/extension.js:1:331
    at Object.<anonymous> (/Users/jpaas/.vscode/extensions/snowcoders.sortier-vscode-2.0.2/dist/extension.js:234:2001)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32222)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28887)
    at Function.f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:61699)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at v._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:30297)
    at v._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:12958)
    at v._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:11931)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

```

**Comment by k2snowman69** [comment]
Sorry for the delayed response, flying all day today. Will investigate tomorrow. My guess is treeshaking failed in a spectacular way.

Note to self: add unit test to do a regex check on output to make sure treeshaking is working as intended.

**Comment by TikiTDO** [comment]
I hit this issue myself, and it looks related to this: https://github.com/evanw/esbuild/issues/1884

When vscode tries to import this module it errors out on the `flow-parser` import, which causes the command to not get loaded.

**Comment by TikiTDO** [comment]
It seems the culprit here is the `"use strict";` in `extension.ts`. If I remove it the build works.

**Comment by k2snowman69** [comment]
I'm being held up by family, if you can create a PR when I get back to my hotel I can merge it and publish

**Comment by k2snowman69** [comment]
@TikiTDO Thanks! That investigation and PR helped speed things up a lot! I just published 2.0.3, waiting for VS to acknowledge it so we can check it.

**Comment by k2snowman69** [comment]
I see success with 2.0.3 on my windows box. I don't have my mac ready, whenever you get a chance let me know if this is successful for you two.

**Comment by TikiTDO** [comment]
@k2snowman69 I tried out 2.0.3 on Linux and it seems to work now

**Comment by k2snowman69** [comment]
Awesome! Now I just have to find a way to write a unit test so it doesn't happen again. Thanks again for the PR, I really appreciate the assist today, you have no idea.

**Comment by TikiTDO** [comment]
If you want to test it, you can do it one of two ways:

1. Just need to mock out the `vscode` import, and ensure that the extension load and runs after a build.
2. Alternatively you can run it inside the vscode dev environment, similar to what you would do with selenium: https://code.visualstudio.com/api/working-with-extensions/testing-extension

**Comment by jpaas** [comment]
Yep all good now. Thanks guys!
